server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  r2dbc:    # 리액티브 애플리케이션이 관계형 데이터베이스를 사용할 수 있도록 설정.
    username: user     # 해당 데이터베이스에 접근 권한이 있는 유저.
    password: password    # 유저의 패스워드.
    url: r2dbc:postgresql://localhost:5432/polardb_order  # 연결하려는 데이터베이스에 대한 R2DBC URL
    pool:
      max-create-connection-time: 2s    # 풀에서 연결 객체 하나를 얻을 때까지 기다릴 수 있는 최대한의 시간.
      initial-size: 5       # 연결 풀의 초기 크기.
      max-size: 10          # 풀이 최대한으로 가질 수 있는 연결의 수.
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  flyway:     # 스프링 데이터 R2DBC가 관리하는 데이터베이스와 동일한 데이터베이스를 플라이웨이가 JDBC 드라이버를 통해 연결.
    # R2DBC에 대해 설정한 값과 같은 유저명과 패스워드 사용.
    user: ${spring.r2dbc.username}    
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order   # R2DBC에 대해 설정한 데이터베이스와 같은 데이터베이스에 연결하기 위해 JDBC 드라이버 사용.
